version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      # Generate on-the-fly Sphinx configuration from Jupyter Book's _config.yml
      - "jupyter-book config sphinx docs/"
      - "mkdir -p docs/_build/html/zips/" 
      - "zip -q -r docs/_build/html/zips/2_Python编程基础.zip  docs/2_Python编程基础"
      - "zip -q -r docs/_build/html/zips/3_NumPy科学计算.zip docs/3_NumPy科学计算"
      
python:
   install:
   - requirements: docs/requirements.txt
#   - method: pip
#     path: .

#formats:
#  - pdf
#  - epub
